// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `myPrinter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MyDemo;

public final class MyPrinterHolder extends Ice.ObjectHolderBase<MyPrinter>
{
    public
    MyPrinterHolder()
    {
    }

    public
    MyPrinterHolder(MyPrinter value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof MyPrinter)
        {
            value = (MyPrinter)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _MyPrinterDisp.ice_staticId();
    }
}
