// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.0
//
// <auto-generated>
//
// Generated from file `myPrinter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package MyDemo;

public interface MyPrinter extends Ice.Object,
                                   _MyPrinterOperations, _MyPrinterOperationsNC
{
    public static final String ice_staticId = "::MyDemo::MyPrinter";

    public static final long serialVersionUID = -1352459592L;
}
